# Generated by Django 4.2.16 on 2025-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymodel",
            name="tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="maincompanymodel",
            name="tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
