# Generated by Django 4.2.16 on 2025-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_storeaddressmodel_store_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maincompanymodel",
            name="logo",
        ),
        migrations.AddField(
            model_name="maincompanymodel",
            name="logo_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
