# Generated by Django 4.2.16 on 2025-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_maincompanymodel_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companymodel",
            name="logo",
        ),
        migrations.AddField(
            model_name="companymodel",
            name="logo_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
