# Generated by Django 4.2.16 on 2025-01-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_companymodel_logo_companymodel_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincompanymodel',
            name='our_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
