# Generated by Django 4.2.16 on 2025-01-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_footercontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterContent',
            new_name='FooterContentModel',
        ),
    ]
